### ISSUE TITLE
Config of mod is reverted to mod default 

### ISSUE THREAD

**Issue by iMex6K** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#19]
Hello

Mc: 1.19.2 
Mod Verision: 4.1.1
Server stopped when editing
No notepad++

everytime after i edit the config of this mod it is reverted back to the default values that are set in the mod itself. 

For example i only want to change:

"Player Limit" = 2

So that the Gen stops as soon as 2 players are on the server. 

Nice would also be an lower amout for Required Free Memory. 

Like: "Required Free Memory" = 512

But the file keeps already reverting when i only want to change a -1 to 2…

It is reverted back to default. 

 [Thread-0/WARN] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file /home/mch/multicraft/servers/server240349/config/PregenConfig.toml is not correct. Correcting

I dont know if this is a failure of your mod or from forge or maybe from bisecthosting… 

A easy solution would be if you could change this values inside of the mod and maybe send me the new mod file. Its just changing two numbers and i already spend so much time in it.

regards

**Comment by Speiger** [comment]
Yeah this is a forge bug not a chunkpregen bug.
But this bug is addressed in the latest patch, that will out in a couple days. Just finished the latest Stress test (60 hours of testing FYI)    
I dropped forges config and implemented IC2Classics Config System which just works a lot better and is also nicer to read.

Please have a bit of patients, i still need to do a few tweaks here and there, but i am aware of this issue i am just doing a bulk health check on this mod at the moment.

ETA within the next 2 weeks in the ABSOLUTE WORST CASE.

**Comment by Speiger** [comment]
Also @iMex6K ping for so you know i answered.

**Comment by Speiger** [comment]
patch released
