### ISSUE TITLE
Trim Command wiki 1.14+

### ISSUE THREAD

**Issue by tnelson2018** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#27]
The trim command examples provided in the wiki are not how the implemented command works. 

I was trying to trim chunks past a 300 chunk radius, but it was asking for multiple 'chunk' values, and throwing an error when ran as the wiki shows.
command: /pregen start delete trim TaskId 300 minecraft:overworld
error: Expected integer ...TaskId 300 minecraft:overworld <-- [HERE]

This also occured with the timed trim.

**Comment by Speiger** [comment]
Good catch. I thought i didn't have this implemented yet. But it is clearly implemented and the documentation was just not updated when i did that xD

But the trim command has a center argument before the radius argument.

Good Catch i will update it later today!
(Please keep this open because its a good reminder)

**Comment by Speiger** [comment]
Done fixed!
