### ISSUE TITLE
[suggestion] Adding the chunk position in the infomation would be nice.

### ISSUE THREAD

**Issue by itsdapi** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#32]
Recently I use pregen to, well pregen. But I found that some chunk have some issues that will cause server to freeze. I would like to know what is pregen currently is generating at what location or what chunks. That will help debugging a lot. 

Anyhow, nice mod, nice tool, greate work!

**Comment by Speiger** [comment]
@itsdapi I am planning a huge translation update to be done soon.
So anything text/UI related would be refreshed.

I really like that idea.
THOUGH it is a bit difficult since i am doing so much work at once, I can't really list everything accurately.
Depending on how it is configured it could have like between 1000 and 5000 chunks being processed at once.

So i will most likely just provide the region it is working in, not the exact positions.

Overall yeah your suggestion is a good idea, just wanted to show there is a few challenges with it ^^"

**Comment by itsdapi** [comment]
> @itsdapi I am planning a huge translation update to be done soon. So anything text/UI related would be refreshed.
> 
> I really like that idea. THOUGH it is a bit difficult since i am doing so much work at once, I can't really list everything accurately. Depending on how it is configured it could have like between 1000 and 5000 chunks being processed at once.
> 
> So i will most likely just provide the region it is working in, not the exact positions.
> 
> Overall yeah your suggestion is a good idea, just wanted to show there is a few challenges with it ^^"

cool, take your time. Absolutely greate work!
