### ISSUE TITLE
Random spontaneous server crash

### ISSUE THREAD

**Issue by GedeonGrays** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#36]
Hello o/

**Minecraft Version:** 1.7.10
**Chunk-Pregenerator Version:** V1.7.10-2.5.3
**Careful Cast Corrector Version:** 2.0
**Chicken Chunk Patcher Version:** 1.1
**KCauldron Version:** Uranium-1710-dev-5-B285-87f3435

**Crash report:** https://pastebin.com/MwQ7m0CG

I was just flying around the world for about an hour, and all of a sudden the server went down. The world was created over a year ago and pregeneration was done immediately. There were no active Chunk-Pregenerator tasks right now.
Then specifically retried as follows:
1) Teleported to coordinates that were not affected by the pregeneration
2) Flew in a straight line towards the new chunks
3) After 5–10 minutes, I got the same crash

I assume the first time this crash occurred, I flew into an area of the world that was unaffected by the initial pregeneration.
So the crash only happens during a new generation.

**Comment by Speiger** [comment]
o/ @GedeonGrays i am pretty sure this is due to Cauldren having async ChunkLoading into minecrafts live world.
Chunk Pregen 1.7.10 isn't compatible with Async Chunk Managment, and doesn't really support custom servers...

(Basically the i am iterating over the chunks and they are modified during that time, which minecraft by default doesn't do)

I will look up a solution, not promising that i will find one, but there won't be a fix for that for this month due to being on a mega patch atm.
So if you need a quick fix you either disable what makes the async chunkloading happen or disable chunkpregen with said software.

**Comment by GedeonGrays** [comment]
Thank you very much for your quick and detailed reply. 

I would like to emphasize that I am in no hurry to solve this problem.
I will wait as long as it takes, if you manage to solve it at all. If not, it will be an extra argument for me to go back to Forge server and give up custom servers.

Thus, all is well.
Thank you for your time and have a great day.

**Comment by Speiger** [comment]
@GedeonGrays this should be either fixed in the latest version or impossible to fix since i list the size in that specific version.
And if it isn't fixed then please ask cauldren to make functions like "size" be thread safe.

**Comment by GedeonGrays** [comment]
Hello o/ 
I will test the latest version of Chunk-Pregenerator on my server and will let you know the result after some time. 
Thanks for your efforts.

UPD:
Flew over 40k blocks in different dimensions, not a single crash the whole time (about 2 hours).
The latest version of CP seems to be working fine (unless of course this crash is a heisenbug). 
Thanks again for your work (☞ﾟヮﾟ)☞
