### ISSUE TITLE
enable dimensions after disabling freezes server

### ISSUE THREAD

**Issue by Sinpox** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#39]
Hi,
have the following problem i disabled dimensions in a modpack to check if the performance is getting better after that (and if it actually reduces the perma loaded chunks which it didnt).

When i now try to enable them again now the server freezes completly (waited 30minutes to check if it comes back) and have to "kill it"

i assume this is not rly an issue of the pregen but more how forge or mc or whatever handles this

but how do i get my dimensions enabled again now? (all add astra dimensions)

**Comment by Speiger** [comment]
o/
Technically disabling the dimension removes the dimension entirely. It doesn't affect other dimensions.

And Chunk Pregenerator manages the dimension unloading in 1.16+ not minecraft or forge.
But that doesn't have to mean that chunk pregen is at fault. It could be that the mod may require the dimension to be present, or needs a specific way of adding the dimension to make it work.

Anyways the fix is rather simple.
- 1: Shut down the server.
- 2: Go into the safe file and into the "data folder"
- 3: Inside the Data folder should be a "pregen_dimensions" file.
- 4: Delete the "pregen_dimensions" file. It is literally only keeping track of dimensions that should be automatically disabled on startup.
- 5: start the server and it should just work :)

**Comment by Sinpox** [comment]
Thanks  (especially for the fast answer), was looking trough many folders for such a file but somehow i missed this...such a easy fix.

**Comment by Speiger** [comment]
@Sinpox no problem :)
