### ISSUE TITLE
RAD2 1.16.5 Server Crash

### ISSUE THREAD

**Issue by duhneller** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#52]
Hello, I am trying to initiate the following: /pregen start gen radius GenExample SQUARE ~ ~ 100
But after a couple of minutes, my server just crashes, stating that a single tic took 600 seconds? Any help would be appreciated. TIA!

[crash-2024-03-20_20.47.41-server.txt](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/files/14681552/crash-2024-03-20_20.47.41-server.txt)

**Comment by Speiger** [comment]
@duhneller please uninstall lootR during pregen.
Its way of replacing chests causes a deadlock likelyhood inside minecraft during pregen.
Note: You have to restart from scratch otherwise you will miss a lot of loot chests.

Saying that: lootR can be added after the pregen is done and it will work just fine.
The problem is the author doesn't know what he is doing.
