### ISSUE TITLE
Chunk Pregenerator hanging

### ISSUE THREAD

**Issue by coolboy2002** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#55]
Hello, thank you for making this tool in the first place.

I installed Chunk-Pregenerator-1.12-4.4.2.jar and ran into the problem that after a while it randomly hangs. The only things I can find back in the logs is a server warning about the ticks being behind (delayed) and the console hanging and showing the task. This happens after a few hours. I can however, still stop the server and restart it and it will go on. The generation is 1250 chunks radius. Help me please :D 
Thank you.

**Comment by Speiger** [comment]
@coolboy2002 what type of hanging?
Maybe a clip of showing what you mean?

Note: This could be due to chunk cascading where a chunk loads another chunk and that chunk loads another chunk.
And chunk pregen can't prevent that, and unless your server dies, this is basically a waiting game, and chunkpregen will check these chunks and skip them if they are properly generated.

**Comment by coolboy2002** [comment]
I can try uploading a clip tomorrow but it will be a bit hard on ubuntu server 22.04 😅
Basically in the console it constantly generates a new message with how many chunks it has loaded of the total amount of the task, how many hours it has ran etc etc. At some point that will hang.

**Comment by coolboy2002** [comment]
Happened again. Had the generator running overnight and 2 hours ago it just stopped and now it doesn't continue on.
![17119568041763251879535572070160](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/72800303/6a10d8cb-b0ab-42ec-a329-894f4c688123)

**Comment by coolboy2002** [comment]
Okay apparently it seems to hang sometimes when it's giving the delay warning of the ticks.

**Comment by Speiger** [comment]
@coolboy2002 yeah that actually validates my point of it being stuck in chunkcascading.
That isn't a bug in chunkpregen but a bug inside minecraft they fixed in 1.13-1.14

But Chunk Pregenerator accounts for these and pauses to not kill the server and makes sure to save frequently so if the server crashes that you won't be stuck forever^^

(This is by the way why you want to pregen your world because since the worldgen is deterministic, think of what would happen if a player loaded said chunk)

**Comment by coolboy2002** [comment]
Sorry man, I did not know this. Thank you so much for explaining. So I did restart the server a few times when it "hanged". Is that a problem or is it fine?

**Comment by Speiger** [comment]
@coolboy2002 it should be fine. Though there is always a chance that this may cause chunks to not generate properly due to it being saved in a weird state.
But that should be always only 1 chunk at most.

Chunkpregen always tries to account for that though and makes a algorithmic check if it could have been that way.
If you want to be 100% sure that nothing happend. Simply run a pregen after that but instead of using "Fastcheckgen" use "normal gen" instead. (fastcheck is the default if you don't put any in)

I wouldn't use normal gen by default but as a secondary check because it skips chunks very slowly and is more there to find mistakes than anything else.

**Comment by coolboy2002** [comment]
Okay, and does Chunk Cascading slow the process down of loading chunks? As it hangs on 23h as of right now and will I really have to do another chunk pregen as I am trying to setup a server and rather hope it could be done quick. Also, is it possible to prerender Galacticraft Planets?
