### ISSUE TITLE
How to configure pregeneration threads?

### ISSUE THREAD

**Issue by TheFlash787** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#81]
As suggested by the title, I'm looking for a way to configure the number of threads that the mod actually uses while pregenerating chunks.

Currently, I'm sitting with an ETA of 40 minutes but only 20-40% of my computer's CPU is being used. Can I increase the number of threads being used to make generation faster?

Thank you!

**Comment by Speiger** [comment]
@TheFlash787 I can't actually schedule the worldgen threads themselves. I have to use Minecrafts scheduler.
and that uses UP TO 6 threads. Depending on how much waiting on dependencies is happening.

If you want to have a faster pregen simply do multiple dimensions at the same time. Since chunkpregen can do that (assuming you have enough free ram) and they won't affect each other much.
