### ISSUE TITLE
[Discussion]: Modding resources for 1.7.10

### ISSUE THREAD

**Issue by mainrs** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#83]
Sorry to bother you, but I couldn't find any other way to contact you directly. I was wondering if you happen to know some resources for modding 1.7.10 specifically.

It's kind of hard to find documentation from 10 years ago. And Forge wasn't really well known for having good documentation to begin with. The only thing that works semi-good is to look at existing, open source mods and see what they do. 

What I am looking for is a system overview kind of documentation: an overview about what Forge provides where. And what parts are provided under the `cpw` umbrella and not the `net.minecraft.forge` package.

Thank you for your contributions, I really love using your mods!

**Comment by Speiger** [comment]
No problem, but I see that you only move on the github space and no other webpage.
Why do i know that?
You never went to Curseforge or any site where chunkpregen can be actually downloaded from.
Because there is a discord link where you can enter a public chat asking directly.

Here are a few resources:
https://letmegooglethat.com/?q=minecraft+1.7.10+modding+tutorial
First thing i would do.
And this is the first thing i found: https://www.youtube.com/playlist?list=PLy11IosblXIExa6zzhjhYNXeBW9o6FhPU

https://www.curseforge.com/minecraft/search?class=mc-mods&version=1.7.10 
Download any mod and use this:
https://github.com/ThexXTURBOXx/Luyten
99% of the mods out there have 0 obfuscation included.
You can decompile the mods and just look what they do.
Though minecraft code is still obfuscated though and mods have to abide by that.
But here is a tool to remedy that: https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000

And this is what i got from 10 minutes of googling and going to curseforge directly.
Note that i randomly picked these together, as if i knew nothing and just did some basic Validating.

If you want more help for 1.7.10 I would suggest you go to the GTNH community since they are actively keeping that version alive and most likely have more documentation on that than me.

Good luck and have fun.

**Comment by mainrs** [comment]
Thanks for the links. I was hoping that some people know some community driven documentation website. I also found the decompilation project, but I am not comfortable in decompiling code I do not own. 

Most modding tutorials I found were the basic ones like adding items, blocks etc.. They never went into too much detail on the internals of Forge.

Yes, I did only look at the GitHub page, my bad! Might be worth adding the discord link here, too! So people don't have to ask again next time :) 

Thanks for your time! I'll head over to the GT community in the hopes that they have a wiki of some sorts!

**Comment by Speiger** [comment]
@mainrs I wouldn't be so hesitant to decompile mods for personal learning.
Copy pasting code from them is a No go if you want to publish your mod/src but if you just want to learn its a perfectly valid solution.
Because you are not bypassing protection but just making language bytecode readable again.
Thats comparable to opening the debug menu in your browser and reading the HTML/JS.

Yes most tutorials end there to be fair at that point you are ment to look at minecrafts code and learn how the engine/game works and do your own stuff. Adding Blocks/Items/entities/etc is just the foundation work you can't really know.

and no problem :)
