### ISSUE TITLE
max radius 500

### ISSUE THREAD

**Issue by makegodhere** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#84]
max radius 500 is so low.
for expamle i have default radius for my servers is 10,000 blocks its equel 625 chunsk (and i need sometimes to increase it).
can we change this limit in config or setup its to unlimit?
creating generate task for every square over 500 for new task with 500 so tiring.

**Comment by Speiger** [comment]
@makegodhere 
There is a limit of 500 radius or 1 million chunk limitation here.
In 1.18.2 or older this can be turned off via config.
If you need bigger limit then 500 you can circumvent it by using the expansion command.
Which also tells you which max radius you can do within the limitations if you went to big.

This was done to give users who need bigger ranges consistently a reason to support the project.
Because every time i asked for "modpack inclusions" or "support in any form" that its not worth it for such a mod.
But when i introduced these limitations all screamed: "Now the best mod is dead"

Thats why this limitation now exists.
Once i decide i no longer want to add content for that mc version i am taking out all limitations and set it free.
Bugfixes will still be done though.

I hope you understand.
